### ISSUE TITLE
inverse transformation of RASTA-PLP

### ISSUE THREAD

**Issue by Navids71** [bootphon/shennong#2]
I'm searching in audio source separation, in order to reconstruct my estimated signal I have to use inverse transformation of the RASTA-PLP, how can I do this inversion of this transform with your package?

**Comment by mmmaat** [comment]
Hi, I do not plan to implement features inversion in shennong. The shennong RASTA-PLP  implementation comes from https://github.com/mystlee/rasta_py and https://labrosa.ee.columbia.edu/matlab/rastamat. They provide some inversion functions, but not for direct RASTA-PLP inversion, this is maybe possible to do it from there code, I don't know.
