### ISSUE TITLE
speech-features cli

### ISSUE THREAD

**Issue by maulikmadhavi** [bootphon/shennong#3]
The conda version does not support `speech-features` command line. 

It always shows:

> fatal error: the following wav files are not found:

The command line works with cloned version of this project. Kindly look into this.

**Comment by mmmaat** [comment]
Hi, thank for reporting! What is your system? What is the exact `speech-features` command you entered?

**Comment by maulikmadhavi** [comment]
I am using the kaldi format wav.scp, 

> speech-features extract --njobs 4 config.yaml wav.scp features.npz

**Comment by mmmaat** [comment]
Well... maybe you are using shennong-0.1 from conda and shennong-0.1.1 from git clone, this would explain the differences you have. A `speech-features --version` will output that.
I fixed a bug related to utterances loading for shennong-0.1.1 : https://github.com/bootphon/shennong/blob/master/CHANGELOG.md#shennong-011
