### ISSUE TITLE
RASTA-PLP

### ISSUE THREAD

**Issue by Ahmad-Suleiman** [bootphon/shennong#5]
I'm looking for RASTA-PLP algorithm (steps and code) in speech recognition

**Comment by mmmaat** [comment]
You have it in shennong, see the [code](https://github.com/bootphon/shennong/blob/master/shennong/features/processor/rastaplp.py) and [documentation](https://docs.syntheticlearner.net/shennong/python/processor/rastaplp.html). This implementation comes from [rastapy](https://github.com/mystlee/rasta_py).
